// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJLsD-mJ8wk2ovIAsAAvvJD4kW-lX7i8',
    appId: '1:613117457356:web:4c1ee3217c222f3dfe2369',
    messagingSenderId: '613117457356',
    projectId: 'ta-recipe-app',
    authDomain: 'ta-recipe-app.firebaseapp.com',
    storageBucket: 'ta-recipe-app.appspot.com',
    measurementId: 'G-DEZQSX669T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPGPRf5CPFzmAZ6bWDyaVxyQ4zNW1DhI',
    appId: '1:613117457356:android:4d79f98c0813e819fe2369',
    messagingSenderId: '613117457356',
    projectId: 'ta-recipe-app',
    storageBucket: 'ta-recipe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ylIN5B2RnuqE1r31fDoby9KQitYSDfw',
    appId: '1:613117457356:ios:3c936cf5079a4f7dfe2369',
    messagingSenderId: '613117457356',
    projectId: 'ta-recipe-app',
    storageBucket: 'ta-recipe-app.appspot.com',
    iosClientId: '613117457356-3dlem350ig5h0reqj292eshh74elhrge.apps.googleusercontent.com',
    iosBundleId: 'com.example.taRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ylIN5B2RnuqE1r31fDoby9KQitYSDfw',
    appId: '1:613117457356:ios:3c936cf5079a4f7dfe2369',
    messagingSenderId: '613117457356',
    projectId: 'ta-recipe-app',
    storageBucket: 'ta-recipe-app.appspot.com',
    iosClientId: '613117457356-3dlem350ig5h0reqj292eshh74elhrge.apps.googleusercontent.com',
    iosBundleId: 'com.example.taRecipeApp',
  );
}
